spring:
  application:
    name: micro-05-mssc-beer-order-service
  #jms properties
  artemis:
    user: artemis
    password: simetraehcapa
  jackson:
    serialization:
      write-dates-as-timestamps: false
      write-date-timestamps-as-nanoseconds: true
  #disable distributed tracing server ( dont want to send log into Zipkin )
  zipkin:
    enabled: false

logging:
  level:
    root: WARN
    pl:
      kukla:
        krzys: DEBUG

server:
  port: 8081

sfg:
  brewery:
    beer-service-host: http://localhost:8080
